### ISSUE TITLE
lab/dbedit, search users globally

### ISSUE THREAD

**Issue by maxfl** [basil-g/juno#4]
In lab/dbEdit/users, current suggestion behavior is the following: when you start typing first/last name the full name is suggested. The suggestions include only people from current institution. The situation becomes a bit difficult in case the institution for a person is not known.

It is suggested to add a possibility to search/suggest from the complete list.

For @ZhiminWangIHEP.

**Comment by maxfl** [comment]
A complete list of shifters would be also very helpful.

**Comment by ZhiminWangIHEP** [comment]
That's it, thank you.

**Comment by basil-g** [comment]
Dear guys,
this issue is all done.
Please have a look.
On dbEdit-> users when you select an Institution - you'll get the list for this institution only and would be able to just ckick on a user in the list. 
But when you select some user's name - you'll get his/her form autocompleted and get the whole shifts users' list to click on.

**Comment by ZhiminWangIHEP** [comment]
Yes, also works well for me.
Thanks,
