### ISSUE TITLE
Calculate the required institute contribution based on shifters list

### ISSUE THREAD

**Issue by maxfl** [basil-g/juno#5]
Currently the institute requirements are calculated based on table, provided by someone. In fact there is enough information to calculate the requirements without providing an input table. 

@ZhiminWangIHEP, please, provide and explain Vasily the formula for such a calculation.

**Comment by ZhiminWangIHEP** [comment]
For the shifter load calculation per year, it is needed to be updated because of the institution and collaborator list is updated each year. 
1. the principle, JUNO IB aggreed to do this update based the list on Sep.30th of each year, then to do the culculation of next year. 
   where we need to use the PhD equiv. to calculate for each institute.
   (except few of JUNO PMT instru. insitute, JINR, Hamburg, SYSU etc. and IHEP is taking its 94%)
   for example: the work load of Instistute of IHEP:
     shift load in 2019 =(IHEP PhD equiv. 2019 * weight_factor (94%)/JUNO  PhD equiv. 2019)* shift load 2019 (234 shifter-week) 
2. shift load: according to the current shift requirements, 1 chief (1.5)+ 3 normal shifters (1.0)+ 2 experts shifters, and 52 weeks per year, that means we need 234 shifter-week per year (not include the 2 expert shifters).
3. the shift schedule, according to the update on July 2018, should to the 12.30 of 2020.

you can find the tree numbers on the table:

PhD equiv. | % PhD equiv. (ratio) | shifts (total)| 2018 (calculated in 2018)

Hope that is clear.
if not, we still need to confirm with Wei.
Thanks,

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Wei just updated us the updated shifter load for 2019 of JUNO PMT as attached.
Could you help to update it on the webpage?
While, following the discussion, I ask you to label the entries for Chinese and not Chinese institutes, that is ok?
Thanks,
[shift-statistics-20181024.xlsx](https://github.com/basil-g/juno/files/2663351/shift-statistics-20181024.xlsx)

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Further requirements from Wei, and some my reply to the requirements:
1. Open shift signups (PMT groups decides how many shifters are needed and when) -> total shifts. All past ones are accurate; ones from next year are accurate; the rests are estimated based on the current information
==> Zhimin: working on this now;
2. collaborator lists (or head counts, this comes from our website or IB) -> loads of each institutes
==> this should not the task of the shifter system?
        or Basil can help to do this with JUNO collaborator database?
3. past statisitics of each institute: yearly and accumulative
==> already there in "Stats"
4. missing shifts of each institute: yearly and accumulative 
==> discussed, impossible to fill into the system, only can keep in the excel for the  missed shifters

**Comment by basil-g** [comment]
@ZhiminWangIHEP 
Dear Zhimin,
I'm summing up all of your comments on the issue and converting them to quiestions and
"inner representation" for a programmer.  I'll start the work ASAP.

**Comment by ZhiminWangIHEP** [comment]
@basil-g 
Get your email today, sorry missed your submit.
I will try to answer your questions.
