### ISSUE TITLE
Block assignment for expired databse

### ISSUE THREAD

**Issue by maxfl** [basil-g/juno#7]
It should be not possible to assign shifters to the database of the past periods.

Issue for @ZhiminWangIHEP.

**Comment by ZhiminWangIHEP** [comment]
I see, this also the same conclusion Basil told me before.
We can do/state in this way.
(In fact, it seems some time, I can sign the shifter in the past week)
Anyway, in this case, we will miss few shifter counts in two situations:
1. before March 2018, when the shifter system didnot working.
2. after March 2018 ~July 2018, few shifters because of the system bugs failed to sign in.
We can manually to count them as did for Wei.

**Comment by maxfl** [comment]
@ZhiminWangIHEP, does this issue requires any work to be done or I may close it?

**Comment by ZhiminWangIHEP** [comment]
yes, please
thanks
